version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: quiltzin
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    networks:
      - nestjs-network
  
  nestjs:
    build: .
    container_name: nestjs-app
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=quiltzin
      - DB_PASS=password1234
      - DB_NAME=mydb
    networks:
      - nestjs-network
  
networks:
  nestjs-network:
    driver: bridge